services:
  serving:
    build:
      context: src/serving
      dockerfile: Dockerfile
    expose:
      - 8000
    environment:
      - RAY_ADDRESS=ray://ray-head:10001
      - RAY_SERVE_ENABLE_RUNTIME_ENV_SETUP=1
      - MLFLOW_TRACKING_URI=http://tracking_server:5000
      - PYTHONPATH=/app
    networks:
      - easymlops_network

networks:
  easymlops_network:
    external: true
