services:
  ray-head:
    build:
      context: src/ray
      dockerfile: Dockerfile
    user: root
    ports:
      - "8265:8265"
      - "10001:10001"
      - "8000:8000"
    volumes:
      - /tmp/ray:/tmp/ray
    command: >
      bash -c "ray start --head
      --dashboard-port=8265
      --dashboard-host=0.0.0.0
      --port=6379
      --redis-password=your_password
      --block
      --temp-dir=/tmp/ray"
    environment:
      - RAY_GRAFANA_HOST=http://grafana:3000
      - RAY_GRAFANA_IFRAME_HOST=http://localhost:3009
      - RAY_PROMETHEUS_HOST=http://prometheus:9090
      - RAY_PROMETHEUS_NAME=Prometheus
    shm_size: 2g
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "2g"
    networks:
      - easymlops_network

  ray-worker:
    build:
      context: src/ray
      dockerfile: Dockerfile
    depends_on:
      - ray-head
    command: bash -c "ray start --address=ray-head:6379 --redis-password=your_password --num-cpus=10 --block"
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "4"
          memory: "4g"
    networks:
      - easymlops_network

networks:
  easymlops_network:
    external: true
